name: wallet_connect_v2
description: Wallet Connect v2 client made in love with dart.
version: 1.0.0
homepage: https://github.com/Orange-Wallet/wallet-connect-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hex: ^0.2.0
  web_socket_channel: ^2.2.0
  uuid: ^3.0.6
  http: ^0.13.5
  cryptography: ^2.0.5
  convert: ^3.0.1
  collection: ^1.16.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  pinenacl: ^0.5.1
  pointycastle: ^3.6.2
  x25519: ^0.1.1
  mockito: ^5.3.2
  bs58: ^1.0.2
  ed25519_edwards: ^0.3.1
  json_rpc_2: ^3.0.2
  event: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.5.3
